---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: grpc-vs
spec:
  host: grpc.example.com
  tls:
    secret: grpc-secret
    cert-manager:
      cluster-issuer: letencrypt-prod
  upstreams:
  - name: grpc-alpha
    service: grpc-alpha
    port: 9080
    type: grpc
  routes:
  - path: /
    service: http-alpha
    action:
      pass: grpc1
---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: grpc-vs
spec:
  host: dgraph.example.com
  tls:
    secret: grpc-secret
  upstreams:
  - name: http-alpha
    service: http-alpha
    port: 6080
    type: http
  routes:
  - path: /
    service: http-alpha
    action:
      pass: grpc1
