repositories:
  - name: itscontained
    url: https://charts.itscontained.io

releases:
  - name: pydgraph-client
    chart: itscontained/raw
    namespace: pydgraph-client
    version:  0.2.5
    values:
      - resources:
          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: pydgraph-client
            spec:
              replicas: 1
              selector:
                matchLabels:
                  app: pydgraph-client
              template:
                metadata:
                  labels:
                    app: pydgraph-client
                spec:
                  containers:
                  - name: pydgraph-client
                    image: {{ requiredEnv "DOCKER_REGISTRY" }}/pydgraph-client:{{ env "BUILD_VERSION" | default "latest" }}
                    env:
                    - name: DGRAPH_ALPHA_SERVER
                      value: {{ env "DGRAPH_RELEASE" | default "dgraph" }}-dgraph-alpha.{{ env "DGRAPH_NS" | default "dgraph" }}.svc.cluster.local
                    resources:
                      requests:
                        memory: "64Mi"
                        cpu: "8m"
                      limits:
                        memory: "128Mi"
                        cpu: "25m"

          - apiVersion: v1
            kind: Service
            metadata:
              labels:
              name: pydgraph-client-headless
            spec:
              clusterIP: None
              ports:
              - name: http
                port: 80
                targetPort: 80
              selector:
                app: pydgraph-client
              type: ClusterIP
    strategicMergePatches:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: pydgraph-client
        spec:
          template:
            metadata:
              annotations:
                consul.hashicorp.com/connect-inject: "true"
                consul.hashicorp.com/transparent-proxy: "true"
