apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dgraph-allow-itsio
  namespace: dgraph
spec:
  podSelector:
    matchLabels:
      app: dgraph
      component: alpha
  ingress:
    # allow access to any pod in the same namespace
    - from:
        - podSelector: {}
    # allow only pods from any namespace that are part of service mesh
    - from:
        - namespaceSelector:
            matchLabels:
              istio-injection: enabled
          podSelector: {}
      ports:
        - port: 9080
        - port: 8080
