---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: pydgraph-client-to-dgraph
spec:
  destination:
    name: dgraph-dgraph-alpha
  sources:
    - name: pydgraph-client
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: pydgraph-client-to-dgraph-grpc
spec:
  destination:
    name: dgraph-dgraph-alpha-grpc
  sources:
    - name: pydgraph-client
      action: allow
