repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: external-dns
    namespace: kube-addons
    chart: bitnami/external-dns
    version: 5.4.4
    values:
      - provider: azure
        azure:
          resourceGroup: {{ requiredEnv "AZ_RESOURCE_GROUP" }}
          tenantId: {{ requiredEnv "AZ_TENANT_ID" }}
          subscriptionId: {{ requiredEnv "AZ_SUBSCRIPTION_ID" }}
          useManagedIdentityExtension: true
          userAssignedIdentityID: {{ requiredEnv "IDENTITY_CLIENT_ID" }}
        logLevel: {{ env "EXTERNALDNS_LOG_LEVEL" | default "debug" }}
        domainFilters:
          - {{ requiredEnv "AZ_DNS_DOMAIN" }}
        txtOwnerId: external-dns
        podLabels:
          aadpodidbinding: external-dns
      {{- if eq "internal" (slice (splitList "." (requiredEnv "AZ_DNS_DOMAIN") -1)) }}
      - provider: azure-private-dns
        azure:
          resourceGroup: {{ requiredEnv "AZ_RESOURCE_GROUP" }}
          tenantId: {{ requiredEnv "AZ_TENANT_ID" }}
          subscriptionId: {{ requiredEnv "AZ_SUBSCRIPTION_ID" }}
          useManagedIdentityExtension: true
          userAssignedIdentityID: {{ requiredEnv "IDENTITY_CLIENT_ID" }}
        logLevel: {{ env "EXTERNALDNS_LOG_LEVEL" | default "debug" }}
        domainFilters:
          - {{ requiredEnv "AZ_PRIVATE_DNS_DOMAIN" }}
        txtOwnerId: external-dns
        podLabels:
          aadpodidbinding: external-dns
      {{- end }}
