openapi: "3.0.0"

info:
  title: Pydgraph Client
  version: "1.0"
servers:
  - url: http://localhost:8080/

paths:
  /health:
    get:
      summary: Health
      description: Returns ok if the server is running
      operationId: greeter_server.health
      responses:
        200:
          description: health response
          content:
            text/plain:
              schema:
                type: string
                example: "ok"
  /SayHello/{name}:
      get:
        summary: Says Hello Name
        description: Returns Hello, {name}!
        operationId: greeter_server.SayHello
        parameters:
          - name: name
            in: path
            description: Name to return
            required: true
            schema:
              type: string
        responses:
          '200':
            description: successful operation
            content:
              text/plain:
                schema:
                  type: string
                  example: "Hello {Name}!"
