repositories:
  - name: dgraph
    url: https://charts.dgraph.io

releases:
  - name: demo
    namespace: dgraph
    chart: dgraph/dgraph
    version: 0.0.17
    values:
      - alpha:
          configFile:
            ## accept list should include local AKS IPs and home office IPs (whatismyip)
            config.yaml: |
              security:
                whitelist: {{ env "DG_ACCEPT_LIST" | default "0.0.0.0/0" | quote }}

        ratel:
          enabled: true

        global:
          ingress:
            enabled: true
            tls:
              - hosts:
                  - alpha.{{ requiredEnv "AZ_DNS_DOMAIN" }}
                  - ratel.{{ requiredEnv "AZ_DNS_DOMAIN" }}
                secretName: tls-secret
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: {{ requiredEnv "ACME_ISSUER" }}
            ratel_hostname: ratel.{{ requiredEnv "AZ_DNS_DOMAIN" }}
            alpha_hostname: alpha.{{ requiredEnv "AZ_DNS_DOMAIN" }}
