repositories:
  # https://artifacthub.io/packages/helm/hashicorp/consul
  - name: hashicorp
    url: https://helm.releases.hashicorp.com

releases:
  - name: consul
    namespace: consul
    chart: hashicorp/consul
    version: 0.48.0
    values:
      - global:
          name: consul
        connectInject:
          enabled: true
        controller:
          enabled: true
        ui:
          enabled: true
          service:
            type: LoadBalancer
