repositories:
  # https://artifacthub.io/packages/helm/dgraph/dgraph/0.0.19
  - name: dgraph
    url: https://charts.dgraph.io

releases:
  - name: dgraph
    namespace: dgraph
    chart: dgraph/dgraph
    version: 0.0.19
    values:
      - image:
          tag: v21.03.2
        alpha:
          configFile:
            config.yaml: |
              security:
                whitelist: {{ env "DG_ACCEPT_LIST" | default "0.0.0.0/0" | quote }}
          service:
            type: ClusterIP
        global:
          ingress:
            enabled: true
            ingressClassName: null
            annotations:
              cert-manager.io/cluster-issuer: {{ requiredEnv "ACME_ISSUER_NAME" }}
              kubernetes.io/ingress.class: nginx
            tls:
              - hosts:
                  - dgraph.{{ requiredEnv "DNS_DOMAIN" }}
                secretName: dgraph-tls-secret
            alpha_hostname: dgraph.{{ requiredEnv "DNS_DOMAIN" }}

          ingress_grpc:
            enabled: true
            ingressClassName: null
            annotations:
              cert-manager.io/cluster-issuer: {{ requiredEnv "ACME_ISSUER_NAME" }}
              nginx.org/grpc-services: "grpc-alpha"
              kubernetes.io/ingress.class: nginx
            tls:
              - hosts:
                  - grpc.{{ requiredEnv "DNS_DOMAIN" }}
                secretName: grpc-tls-secret
            alpha_grpc_hostname: grpc.{{ requiredEnv "DNS_DOMAIN" }}
