repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io
  - name: itscontained
    url: https://charts.itscontained.io

releases:
  - name: external-dns
    namespace: kube-addons
    chart: bitnami/external-dns
    version: 5.4.4
    values:
      - provider: azure
        azure:
          resourceGroup: {{ requiredEnv "AZ_RESOURCE_GROUP" }}
          tenantId: {{ requiredEnv "AZ_TENANT_ID" }}
          subscriptionId: {{ requiredEnv "AZ_SUBSCRIPTION_ID" }}
          useManagedIdentityExtension: true
          userAssignedIdentityID: {{ requiredEnv "IDENTITY_CLIENT_ID" }}
        logLevel: {{ env "EXTERNALDNS_LOG_LEVEL" | default "debug" }}
        domainFilters:
          - {{ requiredEnv "AZ_DNS_DOMAIN" }}
        txtOwnerId: external-dns
        podLabels:
          aadpodidbinding: external-dns

  - name: ingress-nginx
    namespace: kube-addons
    chart: ingress-nginx/ingress-nginx
    version: 4.0.1
    values:
      - controller:
          replicaCount: 2
          nodeSelector:
            kubernetes.io/os: linux
          admissionWebhooks:
            patch:
              nodeSelector:
                kubernetes.io/os: linux
          service:
            externalTrafficPolicy: Local
        defaultBackend:
          nodeSelector:
            kubernetes.io/os: linux

  - name: cert-manager
    namespace: kube-addons
    chart: jetstack/cert-manager
    version: 1.5.3
    values:
      - installCRDs: true
        extraArgs:
          - --cluster-resource-namespace=kube-addons
        global:
          logLevel: 2
        podLabels:
          aadpodidbinding: cert-manager
