repositories:
  - name: dgraph
    url: https://charts.dgraph.io
  # - name: itscontained
  #   url: https://charts.itscontained.io

releases:
  - name: demo
    namespace: dgraph
    chart: dgraph/dgraph
    version: 0.0.17
    values:
      - alpha:
          configFile:
            ## accept list should include local AKS IPs and home office IPs (whatismyip)
            config.yaml: |
              security:
                whitelist: {{ env "DG_ACCEPT_LIST" | default "0.0.0.0/0" | quote }}
