repositories:
  - name: dgraph
    url: https://charts.dgraph.io

releases:
  - name: demo
    namespace: dgraph
    chart: dgraph/dgraph
    version: 0.0.17
    values:
      - alpha:
          configFile:
            config.yaml: |
              security:
                whitelist: {{ env "DG_ACCEPT_LIST" | default "0.0.0.0/0" | quote }}
