Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest: 80, host: 8081
  
  ####### Provision #######
  config.vm.provision "docker", images: %w(httpd:2.4) do |docker|
    docker.run "hello_web",
      image: "httpd:2.4",
      args: "-p 80:80 " +
        "-v /vagrant/public-html:/usr/local/apache2/htdocs/"
  end
end
