repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: external-dns
    namespace: kube-addons
    chart: bitnami/external-dns
    version: 5.1.1
    values:
      - provider: azure
        azure:
          ## When a secret to load azure.json is not specified,
          ## the host's /etc/kubernetes/azure.json will be used
          ##
          ## Deprecated: please use tenantId, subscriptionId, aadClientId and aadClientSecret values instead.
          ##
          secretName: ""
          ## Azure resource group to use
          ##
          cloud: ""
          ## Azure Cloud to use
          ##
          resourceGroup: {{ requiredEnv 'AZ_RESOURCE_GROUP' }}
          tenantId: {{ requiredEnv 'AZ_TENANT_ID' }}
          subscriptionId: {{ requiredEnv 'AZ_SUBSCRIPTION_ID' }}
          ## Azure Application Client ID to use
          ##
          aadClientId: ""
          ## Azure Application Client Secret to use
          ##
          aadClientSecret: ""
          ## If you use Azure MSI, this should be set to true
          ##
          useManagedIdentityExtension: false
          ## If you use Azure MSI, this is Client ID of Azure user-assigned managed identity (optional,
          # system-assigned managed identity is used if empty)
          #
          userAssignedIdentityID: ""
