version: "3.5"
services:
  minio:
    image: minio/minio:RELEASE.2020-09-08T23-05-18Z
    command: gateway azure
    container_name: azure-gateway
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ports:
      - 9000:9000
  client:
    build: .
    container_name: azure-client
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      AZURE_GATEWAY: azure-gateway
    volumes:
      - /root:/root/
    entrypoint:
      - /usr/local/bin/entrypoint.sh
    command:
      - /bin/bash
      - -c
      - while true; do :; done
