repositories:
  - name: itscontained
    url: https://charts.itscontained.io

releases:

  - name: greeter-server
    chart: itscontained/raw
    namespace: greeter-server
    version:  0.2.5
    values:
      - resources:
          - apiVersion: v1
            kind: Service
            metadata:
              name: greeter-server
            spec:
              selector:
                app: greeter-server
              ports:
                - protocol: TCP
                  port: 8080
                  targetPort: 8080
                  name: http
                {{- if ne (env "CCSM_ENABLED") "true" }}
                - protocol: TCP
                  port: 9080
                  targetPort: 9080
                  name: grpc
                {{- end }}

          {{- if eq (env "CCSM_ENABLED") "true" }}
          - apiVersion: v1
            kind: Service
            metadata:
              name: greeter-server-grpc
            spec:
              selector:
                app: greeter-server
              ports:
                - protocol: TCP
                  port: 9080
                  targetPort: 9080
                  name: grpc

          - apiVersion: v1
            kind: ServiceAccount
            metadata:
              name: greeter-server-grpc
          {{- end }}

          - apiVersion: v1
            kind: ServiceAccount
            metadata:
              name: greeter-server

          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: greeter-server
            spec:
              replicas: {{ env "GREETER_REPLICAS" | default 1 }}
              selector:
                matchLabels:
                  app: greeter-server
              template:
                metadata:
                  name: greeter-server
                  labels:
                    app: greeter-server
                  {{- if eq (env "CCSM_ENABLED") "true" }}
                  # https://github.com/hashicorp/consul-k8s/releases/tag/v0.41.0
                  # https://www.consul.io/docs/k8s/connect#kubernetes-pods-with-multiple-ports
                  annotations:
                    'consul.hashicorp.com/connect-inject': 'true'
                    'consul.hashicorp.com/connect-service': 'greeter-server,greeter-server-grpc'
                    'consul.hashicorp.com/connect-service-port': '8080,9080'
                    'consul.hashicorp.com/transparent-proxy': 'false'
                  {{- end }}
                spec:
                  containers:
                    - name: greeter-server
                      image: {{ requiredEnv "DOCKER_REGISTRY" }}/greeter-server
                      ports:
                        - containerPort: 9080
                          name: grpc
                        - containerPort: 8080
                          name: http
                  serviceAccountName: greeter-server

  - name: greeter-client
    chart: itscontained/raw
    namespace: greeter-client
    version:  0.2.5
    values:
      - resources:
          - apiVersion: v1
            kind: Service
            metadata:
              name: greeter-client
            spec:
              selector:
                app: greeter-client
              ports:
                - port: 80

          - apiVersion: v1
            kind: ServiceAccount
            metadata:
              name: greeter-client

          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: greeter-client
            spec:
              replicas: 1
              selector:
                matchLabels:
                  app: greeter-client
              template:
                metadata:
                  name: greeter-client
                  labels:
                    app: greeter-client
                  {{- if eq (env "CCSM_ENABLED") "true" }}
                  annotations:
                    consul.hashicorp.com/connect-inject: 'true'
                    consul.hashicorp.com/connect-service-upstreams: >-
                      greeter-server:8080,greeter-server-grpc:9080
                  {{- end }}
                spec:
                  containers:
                    - name: greeter-client
                      image: {{ requiredEnv "DOCKER_REGISTRY" }}/greeter-server
                      # Just spin & wait forever, we'll use `kubectl exec` to demo
                      command: ['/bin/sh', '-c', '--']
                      args: ['while true; do sleep 30; done;']
                  serviceAccountName: greeter-client
