Vagrant.configure("2") do |config| 
    # config.vm.provision "bootstrap", before: :all, 
    #   type: "shell", path: "./bootstrap.sh"
  
    # Chef Server node
    config.vm.define "chefserver01" do |chefserver|
      chefserver.vm.box = "generic/ubuntu2204"
      chefserver.vm.hostname = "chefserver01.local"
      chefserver.vm.network "private_network", ip: "192.168.50.4"
      chefserver.vm.network 'forwarded_port', guest: 4321, host: 4321
      chefserver.vm.network 'forwarded_port', guest: 9683, host: 9683
      chefserver.vm.network 'forwarded_port', guest: 80, host: 8080
      chefserver.vm.network 'forwarded_port', guest: 443, host: 8443
    end
  
  end
  