Vagrant.configure("2") do |config| 
  # global configuration for all systems
  config.vm.provision "bootstrap", before: :all, 
    type: "shell", path: "./bootstrap.sh"

  # Chef Server node
  config.vm.define "chefserver" do |chefserver|
    chefserver.vm.box = "generic/ubuntu2204" # Virtualbox (x86)
    chefserver.vm.provider "virtualbox" do |vbox|
        vbox.memory = 4048 
    end
    chefserver.vm.hostname = "chefserver01.local"
    chefserver.vm.network "private_network", ip: "192.168.49.3"
    # chefserver.vm.network 'forwarded_port', guest: 4321, host: 4321
    # chefserver.vm.network 'forwarded_port', guest: 9683, host: 9683
    # chefserver.vm.network 'forwarded_port', guest: 80, host: 8080
    # chefserver.vm.network 'forwarded_port', guest: 443, host: 8443
  end

  config.vm.define "chefworkstation" do |chefworkstation|
    chefworkstation.vm.box = "generic/ubuntu2204" # Virtualbox (x86)
    chefworkstation.vm.hostname = "chefworkstation01.local"
    chefworkstation.vm.network "private_network", ip: "192.168.49.4"
  end
end
