Vagrant.configure("2") do |config|
  puts "RUBY_PLATFORM=#{RUBY_PLATFORM}"
  if RUBY_PLATFORM =~ /^x86_64/
    config.vm.box = "generic/ubuntu2204"
    if RUBY_PLATFORM =~ /darwin$/
      config.vm.provider "qemu" do |qe|
        qe.ssh_port = "50025" # change ssh port as needed
        qe.qemu_dir = "/usr/local/share/qemu"
        qe.arch = "x86_64"
        qe.machine = "q35,accel=hvf"
        qe.net_device = "virtio-net-pci"
      end
    end
  elsif RUBY_PLATFORM =~ /arm64.-darwin\d\d$/
    config.vm.box = "perk/ubuntu-2204-arm64"
    # use defaults except for ssh_port
    config.vm.provider "qemu" do |qe|
      qe.ssh_port = "50026" # change ssh port as needed
    end
  elsif  RUBY_PLATFORM == "arm64-darwin"
    HOMEBREW_PREFIX = ENV['HOMEBREW_PREFIX'] || '/opt/homebrew'
    config.vm.box = "perk/ubuntu-2204-arm64"
    config.vm.provider "qemu" do |qe|
      qe.ssh_port = "50025" # change ssh port as needed
      qe.qemu_dir = "#{HOMEBREW_PREFIX}/share/qemu"
    end
  end
  config.vm.network "forwarded_port", guest: 3000, host: 3000
end
