repositories:
  # https://artifacthub.io/packages/helm/cert-manager/cert-manager
  - name: jetstack
    url: https://charts.jetstack.io
  # https://artifacthub.io/packages/helm/bitnami/external-dns
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  # https://artifacthub.io/packages/helm/nginx/nginx-ingress
  - name: nginx-stable
    url: https://helm.nginx.com/stable

releases:
  - name: external-dns
    namespace: kube-addons
    chart: bitnami/external-dns
    version: 6.8.1
    values:
      - provider: google
        google:
          zoneVisibility: public
          project: {{ env "DNS_PROJECT_ID" }}
        serviceAccount:
          annotations:
            # google workgroup identity annotation
            iam.gke.io/gcp-service-account: {{ requiredEnv "DNS_SA_EMAIL" }}
        nodeSelector:
          # deploy on nodes that support workgroup identity
          iam.gke.io/gke-metadata-server-enabled: "true"
        logLevel: {{ env "EXTERNALDNS_LOG_LEVEL" | default "debug" }}
        domainFilters:
          - {{ requiredEnv "DNS_DOMAIN" }}
        txtOwnerId: external-dns
        rbac:
          create: true
          apiVersion: v1
        policy: upsert-only

  - name: cert-manager
    namespace: kube-addons
    chart: jetstack/cert-manager
    version: 1.9.1
    values:
      - installCRDs: true
        extraArgs:
          - --cluster-resource-namespace=kube-addons
        global:
          logLevel: 2
        serviceAccount:
          annotations:
            # google workgroup identity annotation
            iam.gke.io/gcp-service-account: {{ requiredEnv "DNS_SA_EMAIL" }}
        nodeSelector:
          # deploy on nodes that support workgroup identity
          iam.gke.io/gke-metadata-server-enabled: "true"

  - name: nginx-ingress
    namespace: nginx-ingress
    chart: nginx-stable/nginx-ingress
    version: 2.3.0
    values:
      - controller:
          nginxplus: false
          image:
            repository: nginx/nginx-ingress
            tag: 2.3.0
          # NGINX Configmap
          config:
            entries:
              ssl-redirect: "True"
              http2: "True"
          ingressClass: nginx
          # NGINX IC CRDs
          enableCustomResources: true
          enableCertManager: true
          enableExternalDNS: true
          # Prometheus must be installed
          enableLatencyMetrics: false
        nginxServiceMesh:
          enable: false
          enableEgress: false

      - controller:
          replicaCount: 1
          nodeSelector:
            kubernetes.io/os: linux
          admissionWebhooks:
            patch:
              nodeSelector:
                kubernetes.io/os: linux
          service:
            externalTrafficPolicy: Local
        defaultBackend:
          nodeSelector:
            kubernetes.io/os: linux
