repositories:
  - name: itscontained
    url: https://charts.itscontained.io

releases:

  - name: greeter-server
    chart: itscontained/raw
    namespace: greeter-server
    version:  0.2.5
    values:
      - resources:
          - apiVersion: v1
            kind: Service
            metadata:
              name: greeter-server
            spec:
              type: ClusterIP
              # publishNotReadyAddresses: true
              selector:
                app: greeter-server
              ports:
              - name: http
                port: 8080
                targetPort: 8080
              - name: grpc
                port: 9080


          - apiVersion: apps/v1
            kind: StatefulSet
            metadata:
              labels:
                app: greeter-server
              name: greeter-server
            spec:
              podManagementPolicy: OrderedReady
              replicas: {{ env "GREETER_REPLICAS" | default 1 }}
              selector:
                matchLabels:
                  app: greeter-server
              serviceName: greeter-server-headless
              template:
                metadata:
                  annotations:
                    consul.hashicorp.com/connect-inject: "true"
                    consul.hashicorp.com/transparent-proxy: "true"
                  labels:
                    app: greeter-server
                spec:
                  affinity:
                    podAntiAffinity:
                      preferredDuringSchedulingIgnoredDuringExecution:
                      - podAffinityTerm:
                          labelSelector:
                            matchExpressions:
                            - key: component
                              operator: In
                              values:
                              - greeter-server
                          topologyKey: kubernetes.io/hostname
                        weight: 100
                  containers:
                    image: {{ requiredEnv "DOCKER_REGISTRY" }}/greeter-server
                    name: greeter-server
                    ports:
                      - containerPort: 7080
                        name: grpc-internal
                      - containerPort: 8080
                        name: http
                      - containerPort: 9080
                        name: grpc
                    resources:
                      requests:
                        memory: 10Mi
                    volumeMounts:
                    - mountPath: /data
                      name: datadir
                  terminationGracePeriodSeconds: 600
                  volumes:
                  - name: datadir
                    persistentVolumeClaim:
                      claimName: datadir
              updateStrategy:
                type: RollingUpdate
              volumeClaimTemplates:
              - metadata:
                  annotations:
                    volume.alpha.kubernetes.io/storage-class: anything
                  name: datadir
                spec:
                  accessModes:
                  - ReadWriteOnce
                  resources:
                    requests:
                      storage: 10Gi

          - apiVersion: v1
            kind: Service
            metadata:
              labels:
                app: greeter-server
                consul.hashicorp.com/service-ignore: "true"
              name: greeter-server-headless
            spec:
              type: ClusterIP
              clusterIP: None
              ports:
              - name: grpc-internal
                port: 7080
                targetPort: 7080
              selector:
                app: greeter-server

  - name: greeter-client
    chart: itscontained/raw
    namespace: greeter-client
    version:  0.2.5
    values:
      - resources:
          - apiVersion: v1
            kind: Service
            metadata:
              # This name will be the service name in Consul.
              name: greeter-client
            spec:
              selector:
                app: greeter-client
              ports:
                - port: 80

          - apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: greeter-client
            spec:
              replicas: 1
              selector:
                matchLabels:
                  app: greeter-client
              template:
                metadata:
                  name: greeter-client
                  labels:
                    app: greeter-client
                  annotations:
                    'consul.hashicorp.com/connect-inject': 'true'
                spec:
                  containers:
                    - name: greeter-client
                      image: {{ requiredEnv "DOCKER_REGISTRY" }}/greeter-server
                      # Just spin & wait forever, we'll use `kubectl exec` to demo
                      command: ['/bin/sh', '-c', '--']
                      args: ['while true; do sleep 30; done;']
