repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: stable
    url: https://charts.helm.sh/stable
  - name: jaegertracing
    url: https://jaegertracing.github.io/helm-charts
  - name: minio
    url: https://helm.min.io/
  - name: dgraph
    url: https://charts.dgraph.io

releases:
  - name: prometheus
    namespace: {{ env "PROMETHEUS_NAMESPACE" | default "monitoring" }}
    chart: prometheus-community/kube-prometheus-stack
    values:
      - ./values/prometheus-operator.yaml
      - grafana:
          adminPassword: {{ requiredEnv "GRAFANA_ADMIN_PASSWORD" }}
    disableValidation: true

  - name: jaeger
    namespace: observability
    chart: jaegertracing/jaeger
    values:
      - ./jaeger_elasticsearch.yaml
      - storage:
          {{ env "JAEGER_STORAGE_TYPE" | default "cassandra" }}:
            password: {{ requiredEnv "JAEGER_STORAGE_PASSWORD" }}

  - name: minio
    namespace: minio
    chart: minio/minio
    version: 6.3.1
    values:
      - minio_config.yaml
      ## generated by terraform scripts
      - minio_secrets.yaml
      - gcsgateway:
          projectId: {{ requiredEnv "PROJECT_ID" }}

  - name: dgraph
    namespace: default
    chart: dgraph/dgraph
    needs:
      - observability/jaeger
    values:
      - ./values/dgraph_jaeger.yaml
