script_path = './scripts'

Vagrant.configure("2") do |config|
  config.vm.box = "generic/gentoo"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  ####### Provision #######
  config.vm.provision "shell" do |script|
    script.path = "#{script_path}/hello_web.sh"
    script.args = %w(
      www-servers/apache
      apache2
      /var/www/localhost/htdocs
    )
  end
end
