repositories:
  # https://artifacthub.io/packages/helm/nginx/nginx-ingress
  - name: nginx-stable
    url: https://helm.nginx.com/stable

releases:
  - name: nsm
    namespace: nginx-mesh
    chart: nginx-stable/nginx-service-mesh
    values:
      - prometheusAddress: prometheus.nsm-monitoring.svc:9090
        telemetry:
          exporters:
            otlp:
              host: otel-collector.nsm-monitoring.svc
              port: 4317
          samplerRatio: 1
        tracing: null
        mtls:
          mode: permissive # or strict
        autoInjection:
          disable: false
          disabledNamespaces:
            - nsm-monitoring
          # enabledNamespaces:
          #   - dgraph
          #   - ratel
