repositories:
  # https://artifacthub.io/packages/helm/linkerd2/linkerd-control-plane
  - name: linkerd
    url: https://helm.linkerd.io/stable
  # https://artifacthub.io/packages/helm/main/raw
  - name: bedag
    url: https://bedag.github.io/helm-charts/

releases:
  # - name: linkerd-namespace
  #   chart: bedag/raw
  #   version:  1.1.0
  #   values:
  #     - resources:
  #         - kind: Namespace
  #           apiVersion: v1
  #           metadata:
  #             name: linkerd
  #             annotations:
  #               linkerd.io/inject: disabled
  #             labels:
  #               linkerd.io/is-control-plane: "true"
  #               config.linkerd.io/admission-webhooks: disabled
  #               linkerd.io/control-plane-ns: linkerd

  - name: linkerd-crds
    namespace: linkerd
    createNamespace: true
    chart: linkerd/linkerd-crds

  - name: linkerd-control-plane
    namespace: linkerd
    createNamespace: false
    chart: linkerd/linkerd-control-plane
    version: 1.9.4
    needs:
      - linkerd/linkerd-crds
    set:
      - name: identityTrustAnchorsPEM
        file: ./certs/ca.crt
      - name: identity.issuer.tls.crtPEM
        file: ./certs/issuer.crt
      - name: identity.issuer.tls.keyPEM
        file: ./certs/issuer.key
    {{- if eq (env "LINKERD_HA") "true" }}
    values:
        # -- Create PodDisruptionBudget resources for each control plane workload
      - enablePodDisruptionBudget: true
        # -- Specify a deployment strategy for each control plane workload
        deploymentStrategy:
          rollingUpdate:
            maxUnavailable: 1
            maxSurge: 25%
        # -- add PodAntiAffinity to each control plane workload
        enablePodAntiAffinity: true
        # proxy configuration
        proxy:
          resources:
            cpu:
              request: 100m
            memory:
              limit: 250Mi
              request: 20Mi
        # controller configuration
        controllerReplicas: 3
        controllerResources: &controller_resources
          cpu: &controller_resources_cpu
            limit: ""
            request: 100m
          memory:
            limit: 250Mi
            request: 50Mi
        destinationResources: *controller_resources
        # identity configuration
        identityResources:
          cpu: *controller_resources_cpu
          memory:
            limit: 250Mi
            request: 10Mi
        # heartbeat configuration
        heartbeatResources: *controller_resources
        # proxy injector configuration
        proxyInjectorResources: *controller_resources
        webhookFailurePolicy: Fail
        # service profile validator configuration
        spValidatorResources: *controller_resources
    {{- end }}
