repositories:
  # https://artifacthub.io/packages/helm/linkerd2/linkerd-control-plane
  - name: linkerd2
    url: https://helm.linkerd.io/stable

releases:
  - name: linkerd-control-plane
    namespace: linkerd
    chart: inkerd2/linkerd-control-plane
    version: 1.9.4
    set:
    - name: identityTrustAnchorsPEM
      file: cert/ca.crt
    - name: identity.issuer.tls.crtPEM
      file: cert/issuer.crt
    - name: dentity.issuer.tls.keyPEM
      file: cert/issuer.key
    values:
        # -- Create PodDisruptionBudget resources for each control plane workload
      - enablePodDisruptionBudget: true
        # -- Specify a deployment strategy for each control plane workload
        deploymentStrategy:
          rollingUpdate:
            maxUnavailable: 1
            maxSurge: 25%
        # -- add PodAntiAffinity to each control plane workload
        enablePodAntiAffinity: true
        # proxy configuration
        proxy:
          resources:
            cpu:
              request: 100m
            memory:
              limit: 250Mi
              request: 20Mi
        # controller configuration
        controllerReplicas: 3
        controllerResources: &controller_resources
          cpu: &controller_resources_cpu
            limit: ""
            request: 100m
          memory:
            limit: 250Mi
            request: 50Mi
        destinationResources: *controller_resources
        # identity configuration
        identityResources:
          cpu: *controller_resources_cpu
          memory:
            limit: 250Mi
            request: 10Mi
        # heartbeat configuration
        heartbeatResources: *controller_resources
        # proxy injector configuration
        proxyInjectorResources: *controller_resources
        webhookFailurePolicy: Fail
        # service profile validator configuration
        spValidatorResources: *controller_resources
