Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest: 80, host: 8081
  
  ####### Provision #######
  config.vm.provision "docker" do |docker|
    docker.build_image "/vagrant",
      args: "-t example/hello_web"
    docker.run "hello_web",
      image: "example/hello_web:latest",
      args: "-p 80:80"
  end
end
