repositories:
  - name: dgraph
    url: https://charts.dgraph.io
  - name: itscontained
    url: https://charts.itscontained.io

releases:
  - name: demo
    namespace: dgraph
    chart: dgraph/dgraph
    version: 0.0.17
    values:
      - alpha:
          configFile:
            ## accept list should include local AKS IPs and home office IPs (whatismyip)
            config.yaml: |
              security:
                whitelist: {{ env "DG_ACCEPT_LIST" | default "0.0.0.0/0" | quote }}

        ratel:
          enabled: true

  - name: demo-ingress
    chart: itscontained/raw
    namespace: dgraph
    version:  0.2.5
    needs:
      - dgraph/demo
    disableValidation: true
    values:

      - resources:
          - apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              name: demo-dgraph-ingress-http
              labels:
                app: dgraph
                component: alpha
              annotations:
                cert-manager.io/cluster-issuer: {{ requiredEnv "ACME_ISSUER" }}
                nginx.ingress.kubernetes.io/ssl-redirect: "true"
                nginx.ingress.kubernetes.io/backend-protocol: HTTP
                kubernetes.io/ingress.class: nginx
            spec:
              tls:
                - hosts:
                    - "alpha.{{ requiredEnv "AZ_DNS_DOMAIN" }}"
                    - "ratel.{{ requiredEnv "AZ_DNS_DOMAIN" }}"
                  secretName: tls-secret
              rules:
                - host: alpha.{{ requiredEnv "AZ_DNS_DOMAIN" }}
                  http:
                    paths:
                    - backend:
                        service:
                          name: demo-dgraph-alpha
                          port:
                            number: 8080
                      path: /
                      pathType: ImplementationSpecific
                - host: ratel.{{ requiredEnv "AZ_DNS_DOMAIN" }}
                  http:
                    paths:
                    - backend:
                        service:
                          name: demo-dgraph-ratel
                          port:
                            number: 80
                      path: /
                      pathType: ImplementationSpecific

          - apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              name: demo-dgraph-ingress-grpc
              labels:
                app: dgraph
                component: alpha
              annotations:
                cert-manager.io/cluster-issuer: {{ requiredEnv "ACME_ISSUER" }}
                nginx.ingress.kubernetes.io/ssl-redirect: "true"
                nginx.ingress.kubernetes.io/backend-protocol: GRPC
                kubernetes.io/ingress.class: nginx
            spec:
              tls:
                - hosts:
                    - "dgraph.{{ requiredEnv "AZ_DNS_DOMAIN" }}"
                  secretName: tls-secret
              rules:
                - host: dgraph.{{ requiredEnv "AZ_DNS_DOMAIN" }}
                  http:
                    paths:
                    - backend:
                        service:
                          name: demo-dgraph-alpha
                          port:
                            number: 9080
                      path: /
                      pathType: ImplementationSpecific
