apiVersion: v1
kind: Service
metadata:
  # This name will be the service name in Consul.
  name: greeter-server
spec:
  selector:
    app: greeter-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter-server
  template:
    metadata:
      name: greeter-server
      labels:
        app: greeter-server
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
    spec:
      containers:
        - name: greeter-server
          image: darknerd/greeter-server
          ports:
            - containerPort: 9080
              name: grpc
            - containerPort: 8080
              name: http
      # If ACLs are enabled, the serviceAccountName must match the Consul service name.
