apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: joauqin-cluster
  region: us-east-2
  version: "1.14"
# traits of worker nodes
nodeGroups:
  - name: joauqin-cluster-workers
    instanceType: t3.medium
    desiredCapacity: 4
    minSize: 1
    maxSize: 4
    iam:
      # polices added to worker node role
      withAddonPolicies:
        # allows read/write to zones in Route53
        externalDNS: true
        # access to ACM
        certManager: true
