resource_group_name = "devapp"
location            = "westus"
image_publisher     = "Canonical"
image_offer         = "0001-com-ubuntu-server-focal"
image_sku           = "20_04-lts"
computer_name       = "appvm"
admin_username      = "azureuser"
