repositories:
  - name: itscontained
    url: https://charts.itscontained.io

releases:
  - name: pydgraph-client
    chart: itscontained/raw
    namespace: pydgraph-client
    version:  0.2.5
    values:
      - resources:
          - apiVersion: v1
            kind: Pod
            metadata:
              name: aks-ssh
            spec:
              containers:
                - name: aks-ssh
                  image: {{ requiredEnv "AZ_ACR_LOGIN_SERVER" }}/aks-ssh:latest
                  resources:
                    requests:
                      memory: "64Mi"
                      cpu: "80m"
                    limits:
                      memory: "128Mi"
                      cpu: "250m"
